name: Bump snapshot version

on:
  workflow_call:
    inputs:
      next_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version. Specify <major.minor.patch>, e.g. 1.3.0.'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-snapshot-version:
    name: Bump snapshot version
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SDK
        uses: actions/checkout@v4

      - name: Set next version
        run: sed -i -r "s#version=([^\']+)#version=${{ inputs.next_version }}-SNAPSHOT#" gradle.properties

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'embrace-ci[bot]'
          git config --global user.email 'embrace-ci@users.noreply.github.com'

          branch=sdk-version-update-${{ github.run_id }}
          git checkout -b $branch
          git add gradle.properties

          if git diff --cached --quiet; then
            echo "No changes to commit, skipping PR."
          else
            git commit -m "CI/CD: set next version: ${{ inputs.next_version }}-SNAPSHOT"
            git push -f origin $branch
            gh pr create \
                --base main \
                --head $branch \
                --title "CI/CD: set next version: ${{ inputs.next_version }}-SNAPSHOT" \
                --body "This is an autogenerated PR, created by the bump-snapshot-version.yml workflow"
          fi
