name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ released ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Build
        run: ./gradlew assembleRelease check koverXmlReport --stacktrace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: embrace-io/opentelemetry-kotlin
          fail_ci_if_error: false
          files: build/reports/kover/reportRelease.xml
