name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ released ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Build
        run: ./gradlew assembleRelease check koverXmlReport --stacktrace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: embrace-io/opentelemetry-kotlin
          fail_ci_if_error: false
          files: build/reports/kover/reportRelease.xml

      - name: Build Example Apps
        run: ./gradlew :examples:jvm-app:build :examples:android-app:assembleRelease --stacktrace

      - name: Build Telescope App
        run: ./gradlew pTML && cd examples/telescope-app && ./gradlew assembleRelease --stacktrace
